defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

global_params:
    dataset: 'CIFAR10'
    # architecture:  'WideResNet'
    architecture:  'ResNet'
    devices: "auto"


training_params:
    epoch: 100
    batch_size: 1024
    dataloader_workers: 32
    type: "AT"
    # type: "normal"
    note: ""
    lr: 0.05


adversarial_training_params:
    eps: 0.03
    name: "PGD"